const CRYPTO_CURRENCIES = [
    {
        id: 'BTCUSDC',
        name: 'BTC/USDC',
        symbol: 'BTCUSDC',
        iconCode: 1,
        price: 0,
        prevPrice: 0,
        highPrice: 0,
        lowPrice: 0,
        volume: 0,
        priceChangePercent: 0,
        quoteVolume: 0,
    },
    {
        id: 'ETHUSDC',
        name: 'ETH/USDC',
        symbol: 'ETHUSDC',
        iconCode: 1027,
        price: 0,
        prevPrice: 0,
        highPrice: 0,
        lowPrice: 0,
        volume: 0,
        priceChangePercent: 0,
        quoteVolume: 0,
    },
    {
        id: 'BTCUSDT',
        name: 'BTC/USDT',
        symbol: 'BTCUSDT',
        iconCode: 1,
        price: 0,
        prevPrice: 0,
        highPrice: 0,
        lowPrice: 0,
        volume: 0,
        priceChangePercent: 0,
        quoteVolume: 0,
    },
    {
        id: 'USDCUSDT',
        name: 'USDC/USDT',
        symbol: 'USDCUSDT',
        iconCode: 3408,
        price: 0,
        prevPrice: 0,
        highPrice: 0,
        lowPrice: 0,
        volume: 0,
        priceChangePercent: 0,
        quoteVolume: 0,
    },
    {
        id: 'ETHUSDT',
        name: 'ETH/USDT',
        symbol: 'ETHUSDT',
        iconCode: 1027,
        price: 0,
        prevPrice: 0,
        highPrice: 0,
        lowPrice: 0,
        volume: 0,
        priceChangePercent: 0,
        quoteVolume: 0,
    },
    {
        id: 'SOLUSDC',
        name: 'SOL/USDC',
        symbol: 'SOLUSDC',
        iconCode: 5426,
        price: 0,
        prevPrice: 0,
        highPrice: 0,
        lowPrice: 0,
        volume: 0,
        priceChangePercent: 0,
        quoteVolume: 0,
    },
    {
        id: 'ETHBTC',
        name: 'ETH/BTC',
        symbol: 'ETHBTC',
        iconCode: 1027,
        price: 0,
        prevPrice: 0,
        highPrice: 0,
        lowPrice: 0,
        volume: 0,
        priceChangePercent: 0,
        quoteVolume: 0,
    },
    {
        id: 'XRPUSDC',
        name: 'XRP/USDC',
        symbol: 'XRPUSDC',
        iconCode: 52,
        price: 0,
        prevPrice: 0,
        highPrice: 0,
        lowPrice: 0,
        volume: 0,
        priceChangePercent: 0,
        quoteVolume: 0,
    },
    {
        id: 'MATICUSDC',
        name: 'MATIC/USDC',
        symbol: 'MATICUSDC',
        iconCode: 3890,
        price: 0,
        prevPrice: 0,
        highPrice: 0,
        lowPrice: 0,
        volume: 0,
        priceChangePercent: 0,
        quoteVolume: 0,
    },
]
export { CRYPTO_CURRENCIES }